sudo: false

language: go
go:
  - "1.11.x"
  - "1.12.x"
  - "1.x"
env:
  global:
    - GO111MODULE=on
    - GOARCH=amd64
    - GOOS=linux
addons:
  apt:
    packages:
      - python3-pip

before_install:
  - go mod download
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls

script:
  - golint ./...
  - go vet ./...
  - go test -covermode=count -coverprofile=profile.cov ./...
  - goveralls -coverprofile=profile.cov -service=travis-ci

before_deploy:
  - pip3 install --upgrade --user awscli
  - mkdir ./deploy
  - go build -a -ldflags "-s -X main.version=$(git describe --tags --always)" -o ./deploy/app ./cmd/alfalfa

# Needs $CF_TEMPLATE_OUT, $CF_STACKNAME
deploy:
  skip_cleanup: true
  provider: script
  script: bash cloudformation/deploy.sh
  on:
    #tags: true
    go: "1.12.x"
    branch: master

notifications:
  email:
    on_success: never
    on_failure: always
