dist: focal
sudo: true

language: go
go:
  - "1.16.x"
  - "1.x"
env:
  global:
    - GO111MODULE=on
    - GOARCH=amd64
    - GOOS=linux
addons:
  apt:
    update: true
    packages:
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - jq
services:
  - docker

before_install:
  - go mod download
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls
  - docker pull lambci/lambda:go1.x

script:
  - golint ./...
  # use golangci-lint
  - GOLANGCI_LINTER_VERSION=v1.27.0
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin $GOLANGCI_LINTER_VERSION
  - golangci-lint run
  - go vet ./...
  - go test -gcflags=-l -covermode=count -coverprofile=profile.cov ./...
  - goveralls -coverprofile=profile.cov -service=travis-ci || echo "Ignoring failure"
  # build and then run lambda tests
  - ./test/test-lambda.sh

# is NOT executed on pull requests!
before_deploy:
  - pip3 install --upgrade pip
  - pip3 install --upgrade awscli
  - mkdir ./deploy
  - go build -a -ldflags "-s -X main.version=$(git describe --tags --always)" -o ./deploy/app ./cmd/alfalfa

# Needs $CF_TEMPLATE_OUT, $CF_STACKNAME
deploy:
  skip_cleanup: true
  provider: script
  script: bash cloudformation/deploy.sh
  on:
    go: "1.x"
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^development|master$ && $TRAVIS_SECURE_ENV_VARS = "true"

after_deploy:
  # cat test/ask/cli_config | jq -c | sed -e 's#\(["{}|]\)#\\\1#g'
  - mkdir -p ./test/ask
  - echo "$ASK_CONFIG" | jq . > ./test/ask/cli_config
  - sudo chown 1000:1000 ./test/ask/cli_config
  - sudo chmod o+rw ./test
  - ./test/test-dialogs.sh
  - rm -f ./test/ask/cli_config

notifications:
  email:
    on_success: never
    on_failure: always
