sudo: false

language: go
go:
  - "1.11.x"
  - "1.12.x"
  - "1.x"
env:
  global:
    - GO111MODULE=on
    - GOARCH=amd64
    - GOOS=linux
addons:
  apt:
    update: true
    packages:
      - python3-pip
services:
  - docker

before_install:
  - go mod download
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls
  - docker pull lambci/lambda:go1.x

script:
  - golint ./...
  - go vet ./...
  - go test -gcflags=-l -covermode=count -coverprofile=profile.cov ./...
  - goveralls -coverprofile=profile.cov -service=travis-ci
  # build and then run lambda tests
  - ./test/tests.sh

before_deploy:
  - pip3 install --upgrade --user pip
  - pip3 install --upgrade --user setuptools awscli
  - mkdir ./deploy
  - go build -a -ldflags "-s -X main.version=$(git describe --tags --always)" -o ./deploy/app ./cmd/alfalfa

# Needs $CF_TEMPLATE_OUT, $CF_STACKNAME
deploy:
  skip_cleanup: true
  provider: script
  script: bash cloudformation/deploy.sh
  on:
    go: "1.12.x"
    all_branches: true
    condition: $TRAVIS_BRANCH = "master" && $TRAVIS_SECURE_ENV_VARS = "true" # master push or PR (but only from own repo)

notifications:
  email:
    on_success: never
    on_failure: always
