dist: focal
sudo: false

language: go
go:
  - "1.12.x"
  - "1.16.x"
  - "1.x"
env:
  global:
    - GO111MODULE=on
    - GOARCH=amd64
    - GOOS=linux
addons:
  apt:
    update: true
    packages:
      - python3-pip
      - python3-setuptools
      - python3-wheel
services:
  - docker

before_install:
  - go mod download
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls
  - docker pull lambci/lambda:go1.x

script:
  - golint ./...
  - go vet ./...
  - go test -gcflags=-l -covermode=count -coverprofile=profile.cov ./...
  - goveralls -coverprofile=profile.cov -service=travis-ci
  # build and then run lambda tests
  - ./test/test-lambda.sh

# is NOT executed on pull requests!
before_deploy:
  - pip3 install --upgrade pip
  - pip3 install --upgrade awscli
  - mkdir ./deploy
  - go build -a -ldflags "-s -X main.version=$(git describe --tags --always)" -o ./deploy/app ./cmd/alfalfa

# Needs $CF_TEMPLATE_OUT, $CF_STACKNAME
deploy:
  skip_cleanup: true
  provider: script
  script: bash cloudformation/deploy.sh
  on:
    go: "1.x"
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^development|master$ && $TRAVIS_SECURE_ENV_VARS = "true"

after_deploy:
  - ./test/test-dialogs.sh

notifications:
  email:
    on_success: never
    on_failure: always
