sudo: false

language: go
go:
  - "1.12.x"
  - "1.16.x"
  - "1.x"
env:
  global:
    - GO111MODULE=on
    - GOARCH=amd64
    - GOOS=linux
    - DOCKER_CLI_EXPERIMENTAL=enabled
addons:
  apt:
    update: true
    packages:
      - python3-pip
      - jq
services:
  - docker

before_install:
  - docker_conf=$(sudo cat /etc/docker/daemon.json 2>/dev/null || echo "{}")
  - docker_conf=$(echo "$docker_conf" |jq '. + {"experimental":true}')
  - echo "$docker_conf" | sudo tee /etc/docker/daemon.json
  - go mod download
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls
  - docker pull lambci/lambda:go1.x

script:
  - golint ./...
  - go vet ./...
  - go test -gcflags=-l -covermode=count -coverprofile=profile.cov ./...
  - goveralls -coverprofile=profile.cov -service=travis-ci
  # build and then run lambda tests
  - ./test/tests.sh

# is NOT executed on pull requests!
before_deploy:
  - pip3 install --upgrade --user pip
  - pip3 install --upgrade --user setuptools awscli
  - mkdir ./deploy
  - go build -a -ldflags "-s -X main.version=$(git describe --tags --always)" -o ./deploy/app ./cmd/alfalfa

# Needs $CF_TEMPLATE_OUT, $CF_STACKNAME
deploy:
  skip_cleanup: true
  provider: script
  script: bash cloudformation/deploy.sh
  on:
    go: "1.12.x"
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^development|master$ && $TRAVIS_SECURE_ENV_VARS = "true"

notifications:
  email:
    on_success: never
    on_failure: always
