sudo: false

language: go
go:
  - "1.11.x"
  - "1.12.x"
  - "1.x"
env:
  - GO111MODULE=on
  - PROJECT=queryaws
  - CF_TEMPLATE_OUT=alexa-cloudformation.yaml
  - CF_STACKNAME=<you stack name>

before_install:
  - go mod download
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls

script:
  - golint ./...
  - go vet ./...
  - go test -covermode=count -coverprofile=profile.cov ./...
  - goveralls -coverprofile=profile.cov -service=travis-ci

before_deploy:
  - pip install --upgrade --user awscli
  - mkdir ./deploy
  - go build -a -ldflags "-s -X main.Version=$(git describe --tags --always)" -o ./deploy/app ./cmd/queryaws

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    tags: true
    branch: master

notifications:
  email:
    on_success: never
    on_failure: always